
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows

on:
  push:
    branches: [ master, workflow-test, app_path ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        #apt-get update
        #sudo apt-get install git python3-dev python3-pip libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkitgtk-3.0-0 gir1.2-webkit-3.0
    - name: Beeware dependencies
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pip install beeware
    - name: Run tests with pytest
      run: |
        cd src/
        python -m unittest test_app.Test_Profile_Manager.test_swap_xml -v
        python -m unittest test_app.Test_Profile_Manager.test_delete_profile -v
        python -m unittest test_app.Test_Profile_Manager.test_create_profile -v
        python -m unittest test_app.Test_Profile_Manager.test_load_profile -v
        python -m unittest test_app.Test_Profile_Manager.test_get_ethnic -v
        python -m unittest test_app.Test_XML_Parser -v
        python -m unittest test_app.Test_RTF_Parser -v
        python -m unittest test_app.Test_Config_Manager -v
        python -m unittest test_app.Test_Xml_Writing -v
        python -m unittest test_mapper.Test_Mapper_Generate_Mapping -v
        python -m unittest test_mapper.Test_Mapper_Preserve_Mapping -v
        python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping -v
    - name: Build
      run: |
        briefcase create
        briefcase build
        briefcase package
    - name: Save Installer
      uses: actions/upload-artifact@v1
      with:
        name: NewGAN-Manager-Installer-Win
        path: windows\NewGAN Manager-1.0.0.msi
